<a href="https://colab.research.google.com/github/akshansh9336/Akshansh-Singh/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [8]:
array = np.array([[10,20],[30,40],[50,60],[70,80]])
print(array)

[[10 20]
 [30 40]
 [50 60]
 [70 80]]


In [9]:
print(array.ndim)

2


In [10]:
print(array.shape)

(4, 2)


In [11]:
print(array.shape)
print(array.size)
print(array.dtype)

(4, 2)
8
int64


In [14]:
array = np.array([[10,20,30],[60,40,50]])
print(array)

[[10 20 30]
 [60 40 50]]


In [15]:
array =np.array([[10,20,30,40,50]])
print(array)

[[10 20 30 40 50]]


In [17]:
print(array[0,0])

10


In [18]:
print(array[1:3])

[]


In [28]:
a=np.array([10,20,30])
print(a)

[10 20 30]


In [26]:
b=np.array([70,80,90])
print(b)

[70 80 90]


In [35]:
print(a+b)
print(b-a)
print(a*b)
print(a/b)
print(a**2)

[ 80 100 120]
[60 60 60]
[ 700 1600 2700]
[0.14285714 0.25       0.33333333]
[100 400 900]


In [37]:
print(np.sqrt(a))     # to find the sq root
print(np.power(a,3))  # for n exponent

[3.16227766 4.47213595 5.47722558]
[ 1000  8000 27000]
